<?php

declare(strict_types=1);

namespace App\Enums;

class CountriesEnum
{
    /**
     * Returning countries codes and titles etc.
     *
     * @return array
     */
    public function getCountries(): array
    {
        return [
                0 => [
                        'id'         => '1',
                        'code'       => 'ru',
                        'title'      => 'Russia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                1 => [
                        'id'         => '2',
                        'code'       => 'ua',
                        'title'      => 'Ukraine',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                2 => [
                        'id'         => '3',
                        'code'       => 'by',
                        'title'      => 'Belarus',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                3 => [
                        'id'         => '4',
                        'code'       => 'kz',
                        'title'      => 'Kazakhstan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                4 => [
                        'id'         => '5',
                        'code'       => 'az',
                        'title'      => 'Azerbaijan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                5 => [
                        'id'         => '6',
                        'code'       => 'am',
                        'title'      => 'Armenia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                6 => [
                        'id'         => '7',
                        'code'       => 'ge',
                        'title'      => 'Georgia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                7 => [
                        'id'         => '8',
                        'code'       => 'il',
                        'title'      => 'Israel',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                8 => [
                        'id'         => '9',
                        'code'       => 'us',
                        'title'      => 'USA',
                        'picture_id' => null,
                        'sort'       => '1001',
                    ],
                9 => [
                        'id'         => '10',
                        'code'       => 'ca',
                        'title'      => 'Canada',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                10 => [
                        'id'         => '11',
                        'code'       => 'kg',
                        'title'      => 'Kyrgyzstan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                11 => [
                        'id'         => '12',
                        'code'       => 'lv',
                        'title'      => 'Latvia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                12 => [
                        'id'         => '13',
                        'code'       => 'lt',
                        'title'      => 'Lithuania',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                13 => [
                        'id'         => '14',
                        'code'       => 'ee',
                        'title'      => 'Estonia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                14 => [
                        'id'         => '15',
                        'code'       => 'md',
                        'title'      => 'Moldova',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                15 => [
                        'id'         => '16',
                        'code'       => 'tj',
                        'title'      => 'Tajikistan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                16 => [
                        'id'         => '17',
                        'code'       => 'tm',
                        'title'      => 'Turkmenistan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                17 => [
                        'id'         => '18',
                        'code'       => 'uz',
                        'title'      => 'Uzbekistan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                18 => [
                        'id'         => '19',
                        'code'       => 'au',
                        'title'      => 'Australia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                19 => [
                        'id'         => '20',
                        'code'       => 'at',
                        'title'      => 'Austria',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                20 => [
                        'id'         => '21',
                        'code'       => 'al',
                        'title'      => 'Albania',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                21 => [
                        'id'         => '22',
                        'code'       => 'dz',
                        'title'      => 'Algeria',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                22 => [
                        'id'         => '23',
                        'code'       => 'as',
                        'title'      => 'American Samoa',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                23 => [
                        'id'         => '24',
                        'code'       => 'ai',
                        'title'      => 'Anguilla',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                24 => [
                        'id'         => '25',
                        'code'       => 'ao',
                        'title'      => 'Angola',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                25 => [
                        'id'         => '26',
                        'code'       => 'ad',
                        'title'      => 'Andorra',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                26 => [
                        'id'         => '27',
                        'code'       => 'ag',
                        'title'      => 'Antigua and Barbuda',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                27 => [
                        'id'         => '28',
                        'code'       => 'ar',
                        'title'      => 'Argentina',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                28 => [
                        'id'         => '29',
                        'code'       => 'aw',
                        'title'      => 'Aruba',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                29 => [
                        'id'         => '30',
                        'code'       => 'af',
                        'title'      => 'Afghanistan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                30 => [
                        'id'         => '31',
                        'code'       => 'bs',
                        'title'      => 'Bahamas',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                31 => [
                        'id'         => '32',
                        'code'       => 'bd',
                        'title'      => 'Bangladesh',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                32 => [
                        'id'         => '33',
                        'code'       => 'bb',
                        'title'      => 'Barbados',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                33 => [
                        'id'         => '34',
                        'code'       => 'bh',
                        'title'      => 'Bahrain',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                34 => [
                        'id'         => '35',
                        'code'       => 'bz',
                        'title'      => 'Belize',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                35 => [
                        'id'         => '36',
                        'code'       => 'be',
                        'title'      => 'Belgium',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                36 => [
                        'id'         => '37',
                        'code'       => 'bj',
                        'title'      => 'Benin',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                37 => [
                        'id'         => '38',
                        'code'       => 'bm',
                        'title'      => 'Bermuda',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                38 => [
                        'id'         => '39',
                        'code'       => 'bg',
                        'title'      => 'Bulgaria',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                39 => [
                        'id'         => '40',
                        'code'       => 'bo',
                        'title'      => 'Bolivia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                40 => [
                        'id'         => '41',
                        'code'       => 'ba',
                        'title'      => 'Bosnia and Herzegovina',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                41 => [
                        'id'         => '42',
                        'code'       => 'bw',
                        'title'      => 'Botswana',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                42 => [
                        'id'         => '43',
                        'code'       => 'br',
                        'title'      => 'Brazil',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                43 => [
                        'id'         => '44',
                        'code'       => 'bn',
                        'title'      => 'Brunei Darussalam',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                44 => [
                        'id'         => '45',
                        'code'       => 'bf',
                        'title'      => 'Burkina Faso',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                45 => [
                        'id'         => '46',
                        'code'       => 'bi',
                        'title'      => 'Burundi',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                46 => [
                        'id'         => '47',
                        'code'       => 'bt',
                        'title'      => 'Bhutan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                47 => [
                        'id'         => '48',
                        'code'       => 'vu',
                        'title'      => 'Vanuatu',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                48 => [
                        'id'         => '49',
                        'code'       => 'uk',
                        'title'      => 'United Kingdom',
                        'picture_id' => null,
                        'sort'       => '1000',
                    ],
                49 => [
                        'id'         => '50',
                        'code'       => 'hu',
                        'title'      => 'Hungary',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                50 => [
                        'id'         => '51',
                        'code'       => 've',
                        'title'      => 'Venezuela',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                51 => [
                        'id'         => '52',
                        'code'       => 'vg',
                        'title'      => 'British Virgin Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                52 => [
                        'id'         => '53',
                        'code'       => 'vi',
                        'title'      => 'US Virgin Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                53 => [
                        'id'         => '54',
                        'code'       => 'bes',
                        'title'      => 'East Timor',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                54 => [
                        'id'         => '55',
                        'code'       => 'vn',
                        'title'      => 'Vietnam',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                55 => [
                        'id'         => '56',
                        'code'       => 'ga',
                        'title'      => 'Gabon',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                56 => [
                        'id'         => '57',
                        'code'       => 'ht',
                        'title'      => 'Haiti',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                57 => [
                        'id'         => '58',
                        'code'       => 'gy',
                        'title'      => 'Guyana',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                58 => [
                        'id'         => '59',
                        'code'       => 'gm',
                        'title'      => 'Gambia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                59 => [
                        'id'         => '60',
                        'code'       => 'gh',
                        'title'      => 'Ghana',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                60 => [
                        'id'         => '61',
                        'code'       => 'gp',
                        'title'      => 'Guadeloupe',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                61 => [
                        'id'         => '62',
                        'code'       => 'gt',
                        'title'      => 'Guatemala',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                62 => [
                        'id'         => '63',
                        'code'       => 'gn',
                        'title'      => 'Guinea',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                63 => [
                        'id'         => '64',
                        'code'       => 'gw',
                        'title'      => 'Guinea-Bissau',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                64 => [
                        'id'         => '65',
                        'code'       => 'de',
                        'title'      => 'Germany',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                65 => [
                        'id'         => '66',
                        'code'       => 'gi',
                        'title'      => 'Gibraltar',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                66 => [
                        'id'         => '67',
                        'code'       => 'hn',
                        'title'      => 'Honduras',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                67 => [
                        'id'         => '68',
                        'code'       => 'hk',
                        'title'      => 'Hong Kong',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                68 => [
                        'id'         => '69',
                        'code'       => 'gd',
                        'title'      => 'Grenada',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                69 => [
                        'id'         => '70',
                        'code'       => 'gl',
                        'title'      => 'Greenland',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                70 => [
                        'id'         => '71',
                        'code'       => 'gr',
                        'title'      => 'Greece',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                71 => [
                        'id'         => '72',
                        'code'       => 'cw',
                        'title'      => 'Guam',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                72 => [
                        'id'         => '73',
                        'code'       => 'dk',
                        'title'      => 'Denmark',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                73 => [
                        'id'         => '74',
                        'code'       => 'dm',
                        'title'      => 'Dominica',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                74 => [
                        'id'         => '75',
                        'code'       => 'do',
                        'title'      => 'Dominican Republic',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                75 => [
                        'id'         => '76',
                        'code'       => 'eg',
                        'title'      => 'Egypt',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                76 => [
                        'id'         => '77',
                        'code'       => 'zm',
                        'title'      => 'Zambia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                77 => [
                        'id'         => '78',
                        'code'       => 'eh',
                        'title'      => 'Western Sahara',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                78 => [
                        'id'         => '79',
                        'code'       => 'zw',
                        'title'      => 'Zimbabwe',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                79 => [
                        'id'         => '80',
                        'code'       => 'in',
                        'title'      => 'India',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                80 => [
                        'id'         => '81',
                        'code'       => 'id',
                        'title'      => 'Indonesia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                81 => [
                        'id'         => '82',
                        'code'       => 'jo',
                        'title'      => 'Jordan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                82 => [
                        'id'         => '83',
                        'code'       => 'iq',
                        'title'      => 'Iraq',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                83 => [
                        'id'         => '84',
                        'code'       => 'ir',
                        'title'      => 'Iran',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                84 => [
                        'id'         => '85',
                        'code'       => 'ie',
                        'title'      => 'Ireland',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                85 => [
                        'id'         => '86',
                        'code'       => 'is',
                        'title'      => 'Iceland',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                86 => [
                        'id'         => '87',
                        'code'       => 'es',
                        'title'      => 'Spain',
                        'picture_id' => null,
                        'sort'       => '998',
                    ],
                87 => [
                        'id'         => '88',
                        'code'       => 'it',
                        'title'      => 'Italy',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                88 => [
                        'id'         => '89',
                        'code'       => 'ye',
                        'title'      => 'Yemen',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                89 => [
                        'id'         => '90',
                        'code'       => 'cv',
                        'title'      => 'Cape Verde',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                90 => [
                        'id'         => '91',
                        'code'       => 'kh',
                        'title'      => 'Cambodia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                91 => [
                        'id'         => '92',
                        'code'       => 'cm',
                        'title'      => 'Cameroon',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                92 => [
                        'id'         => '93',
                        'code'       => 'qa',
                        'title'      => 'Qatar',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                93 => [
                        'id'         => '94',
                        'code'       => 'ke',
                        'title'      => 'Kenya',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                94 => [
                        'id'         => '95',
                        'code'       => 'cy',
                        'title'      => 'Cyprus',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                95 => [
                        'id'         => '96',
                        'code'       => 'ki',
                        'title'      => 'Kiribati',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                96 => [
                        'id'         => '97',
                        'code'       => 'cn',
                        'title'      => 'China',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                97 => [
                        'id'         => '98',
                        'code'       => 'co',
                        'title'      => 'Colombia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                98 => [
                        'id'         => '99',
                        'code'       => 'km',
                        'title'      => 'Comoros',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                99 => [
                        'id'         => '100',
                        'code'       => 'cg',
                        'title'      => 'Congo',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                100 => [
                        'id'         => '101',
                        'code'       => 'cd',
                        'title'      => 'Congo, Democratic Republic',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                101 => [
                        'id'         => '102',
                        'code'       => 'cr',
                        'title'      => 'Costa Rica',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                102 => [
                        'id'         => '103',
                        'code'       => 'ci',
                        'title'      => 'Côte d`Ivoire',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                103 => [
                        'id'         => '104',
                        'code'       => 'cu',
                        'title'      => 'Cuba',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                104 => [
                        'id'         => '105',
                        'code'       => 'kw',
                        'title'      => 'Kuwait',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                105 => [
                        'id'         => '106',
                        'code'       => 'la',
                        'title'      => 'Laos',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                106 => [
                        'id'         => '107',
                        'code'       => 'ls',
                        'title'      => 'Lesotho',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                107 => [
                        'id'         => '108',
                        'code'       => 'lr',
                        'title'      => 'Liberia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                108 => [
                        'id'         => '109',
                        'code'       => 'lb',
                        'title'      => 'Lebanon',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                109 => [
                        'id'         => '110',
                        'code'       => 'ly',
                        'title'      => 'Libya',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                110 => [
                        'id'         => '111',
                        'code'       => 'li',
                        'title'      => 'Liechtenstein',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                111 => [
                        'id'         => '112',
                        'code'       => 'lu',
                        'title'      => 'Luxembourg',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                112 => [
                        'id'         => '113',
                        'code'       => 'mu',
                        'title'      => 'Mauritius',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                113 => [
                        'id'         => '114',
                        'code'       => 'mr',
                        'title'      => 'Mauritania',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                114 => [
                        'id'         => '115',
                        'code'       => 'mg',
                        'title'      => 'Madagascar',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                115 => [
                        'id'         => '116',
                        'code'       => 'mo',
                        'title'      => 'Macau',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                116 => [
                        'id'         => '117',
                        'code'       => 'mk',
                        'title'      => 'Macedonia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                117 => [
                        'id'         => '118',
                        'code'       => 'mw',
                        'title'      => 'Malawi',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                118 => [
                        'id'         => '119',
                        'code'       => 'my',
                        'title'      => 'Malaysia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                119 => [
                        'id'         => '120',
                        'code'       => 'ml',
                        'title'      => 'Mali',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                120 => [
                        'id'         => '121',
                        'code'       => 'mv',
                        'title'      => 'Maldives',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                121 => [
                        'id'         => '122',
                        'code'       => 'mt',
                        'title'      => 'Malta',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                122 => [
                        'id'         => '123',
                        'code'       => 'ma',
                        'title'      => 'Morocco',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                123 => [
                        'id'         => '124',
                        'code'       => 'mq',
                        'title'      => 'Martinique',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                124 => [
                        'id'         => '125',
                        'code'       => 'mh',
                        'title'      => 'Marshall Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                125 => [
                        'id'         => '126',
                        'code'       => 'mx',
                        'title'      => 'Mexico',
                        'picture_id' => null,
                        'sort'       => '995',
                    ],
                126 => [
                        'id'         => '127',
                        'code'       => 'tl',
                        'title'      => 'Micronesia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                127 => [
                        'id'         => '128',
                        'code'       => 'mz',
                        'title'      => 'Mozambique',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                128 => [
                        'id'         => '129',
                        'code'       => 'mc',
                        'title'      => 'Monaco',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                129 => [
                        'id'         => '130',
                        'code'       => 'mn',
                        'title'      => 'Mongolia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                130 => [
                        'id'         => '131',
                        'code'       => 'ms',
                        'title'      => 'Montserrat',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                131 => [
                        'id'         => '132',
                        'code'       => 'mm',
                        'title'      => 'Myanmar',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                132 => [
                        'id'         => '133',
                        'code'       => 'na',
                        'title'      => 'Namibia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                133 => [
                        'id'         => '134',
                        'code'       => 'nr',
                        'title'      => 'Nauru',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                134 => [
                        'id'         => '135',
                        'code'       => 'np',
                        'title'      => 'Nepal',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                135 => [
                        'id'         => '136',
                        'code'       => 'ne',
                        'title'      => 'Niger',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                136 => [
                        'id'         => '137',
                        'code'       => 'ng',
                        'title'      => 'Nigeria',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                137 => [
                        'id'         => '138',
                        'code'       => 'gu',
                        'title'      => 'Curaçao',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                138 => [
                        'id'         => '139',
                        'code'       => 'nl',
                        'title'      => 'Netherlands',
                        'picture_id' => null,
                        'sort'       => '999',
                    ],
                139 => [
                        'id'         => '140',
                        'code'       => 'ni',
                        'title'      => 'Nicaragua',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                140 => [
                        'id'         => '141',
                        'code'       => 'nu',
                        'title'      => 'Niue',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                141 => [
                        'id'         => '142',
                        'code'       => 'nz',
                        'title'      => 'New Zealand',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                142 => [
                        'id'         => '143',
                        'code'       => 'nc',
                        'title'      => 'New Caledonia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                143 => [
                        'id'         => '144',
                        'code'       => 'no',
                        'title'      => 'Norway',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                144 => [
                        'id'         => '145',
                        'code'       => 'ae',
                        'title'      => 'United Arab Emirates',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                145 => [
                        'id'         => '146',
                        'code'       => 'om',
                        'title'      => 'Oman',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                146 => [
                        'id'         => '147',
                        'code'       => 'im',
                        'title'      => 'Isle of Man',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                147 => [
                        'id'         => '148',
                        'code'       => 'nf',
                        'title'      => 'Norfolk Island',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                148 => [
                        'id'         => '149',
                        'code'       => 'ky',
                        'title'      => 'Cayman Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                149 => [
                        'id'         => '150',
                        'code'       => 'ck',
                        'title'      => 'Cook Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                150 => [
                        'id'         => '151',
                        'code'       => 'tc',
                        'title'      => 'Turks and Caicos Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                151 => [
                        'id'         => '152',
                        'code'       => 'pk',
                        'title'      => 'Pakistan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                152 => [
                        'id'         => '153',
                        'code'       => 'pw',
                        'title'      => 'Palau',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                153 => [
                        'id'         => '154',
                        'code'       => 'ps',
                        'title'      => 'Palestine',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                154 => [
                        'id'         => '155',
                        'code'       => 'pa',
                        'title'      => 'Panama',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                155 => [
                        'id'         => '156',
                        'code'       => 'pg',
                        'title'      => 'Papua New Guinea',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                156 => [
                        'id'         => '157',
                        'code'       => 'py',
                        'title'      => 'Paraguay',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                157 => [
                        'id'         => '158',
                        'code'       => 'pe',
                        'title'      => 'Peru',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                158 => [
                        'id'         => '159',
                        'code'       => 'pn',
                        'title'      => 'Pitcairn Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                159 => [
                        'id'         => '160',
                        'code'       => 'pl',
                        'title'      => 'Poland',
                        'picture_id' => null,
                        'sort'       => '996',
                    ],
                160 => [
                        'id'         => '161',
                        'code'       => 'pt',
                        'title'      => 'Portugal',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                161 => [
                        'id'         => '162',
                        'code'       => 'fm',
                        'title'      => 'Puerto Rico',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                162 => [
                        'id'         => '163',
                        'code'       => 're',
                        'title'      => 'Réunion',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                163 => [
                        'id'         => '164',
                        'code'       => 'rw',
                        'title'      => 'Rwanda',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                164 => [
                        'id'         => '165',
                        'code'       => 'ro',
                        'title'      => 'Romania',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                165 => [
                        'id'         => '166',
                        'code'       => 'sv',
                        'title'      => 'El Salvador',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                166 => [
                        'id'         => '167',
                        'code'       => 'ws',
                        'title'      => 'Samoa',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                167 => [
                        'id'         => '168',
                        'code'       => 'sm',
                        'title'      => 'San Marino',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                168 => [
                        'id'         => '169',
                        'code'       => 'st',
                        'title'      => 'São Tomé and Príncipe',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                169 => [
                        'id'         => '170',
                        'code'       => 'sa',
                        'title'      => 'Saudi Arabia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                170 => [
                        'id'         => '171',
                        'code'       => 'sz',
                        'title'      => 'Swaziland',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                171 => [
                        'id'         => '172',
                        'code'       => 'sh',
                        'title'      => 'Saint Helena',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                172 => [
                        'id'         => '173',
                        'code'       => 'kp',
                        'title'      => 'North Korea',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                173 => [
                        'id'         => '174',
                        'code'       => 'mp',
                        'title'      => 'Northern Mariana Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                174 => [
                        'id'         => '175',
                        'code'       => 'sc',
                        'title'      => 'Seychelles',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                175 => [
                        'id'         => '176',
                        'code'       => 'sn',
                        'title'      => 'Senegal',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                176 => [
                        'id'         => '177',
                        'code'       => 'vc',
                        'title'      => 'Saint Vincent and the Grenadines',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                177 => [
                        'id'         => '178',
                        'code'       => 'kn',
                        'title'      => 'Saint Kitts and Nevis',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                178 => [
                        'id'         => '179',
                        'code'       => 'lc',
                        'title'      => 'Saint Lucia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                179 => [
                        'id'         => '180',
                        'code'       => 'pm',
                        'title'      => 'Saint Pierre and Miquelon',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                180 => [
                        'id'         => '181',
                        'code'       => 'pr',
                        'title'      => 'Serbia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                181 => [
                        'id'         => '182',
                        'code'       => 'sg',
                        'title'      => 'Singapore',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                182 => [
                        'id'         => '183',
                        'code'       => 'sy',
                        'title'      => 'Syria',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                183 => [
                        'id'         => '184',
                        'code'       => 'sk',
                        'title'      => 'Slovakia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                184 => [
                        'id'         => '185',
                        'code'       => 'si',
                        'title'      => 'Slovenia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                185 => [
                        'id'         => '186',
                        'code'       => 'sb',
                        'title'      => 'Solomon Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                186 => [
                        'id'         => '187',
                        'code'       => 'so',
                        'title'      => 'Somalia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                187 => [
                        'id'         => '188',
                        'code'       => 'sd',
                        'title'      => 'Sudan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                188 => [
                        'id'         => '189',
                        'code'       => 'sr',
                        'title'      => 'Suriname',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                189 => [
                        'id'         => '190',
                        'code'       => 'sl',
                        'title'      => 'Sierra Leone',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                190 => [
                        'id'         => '191',
                        'code'       => 'th',
                        'title'      => 'Thailand',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                191 => [
                        'id'         => '192',
                        'code'       => 'tw',
                        'title'      => 'Taiwan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                192 => [
                        'id'         => '193',
                        'code'       => 'tz',
                        'title'      => 'Tanzania',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                193 => [
                        'id'         => '194',
                        'code'       => 'tg',
                        'title'      => 'Togo',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                194 => [
                        'id'         => '195',
                        'code'       => 'tk',
                        'title'      => 'Tokelau',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                195 => [
                        'id'         => '196',
                        'code'       => 'to',
                        'title'      => 'Tonga',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                196 => [
                        'id'         => '197',
                        'code'       => 'tt',
                        'title'      => 'Trinidad and Tobago',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                197 => [
                        'id'         => '198',
                        'code'       => 'tv',
                        'title'      => 'Tuvalu',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                198 => [
                        'id'         => '199',
                        'code'       => 'tn',
                        'title'      => 'Tunisia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                199 => [
                        'id'         => '200',
                        'code'       => 'tr',
                        'title'      => 'Turkey',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                200 => [
                        'id'         => '201',
                        'code'       => 'ug',
                        'title'      => 'Uganda',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                201 => [
                        'id'         => '202',
                        'code'       => 'wf',
                        'title'      => 'Wallis and Futuna',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                202 => [
                        'id'         => '203',
                        'code'       => 'uy',
                        'title'      => 'Uruguay',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                203 => [
                        'id'         => '204',
                        'code'       => 'fo',
                        'title'      => 'Faroe Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                204 => [
                        'id'         => '205',
                        'code'       => 'fj',
                        'title'      => 'Fiji',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                205 => [
                        'id'         => '206',
                        'code'       => 'ph',
                        'title'      => 'Philippines',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                206 => [
                        'id'         => '207',
                        'code'       => 'fi',
                        'title'      => 'Finland',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                207 => [
                        'id'         => '208',
                        'code'       => 'fk',
                        'title'      => 'Falkland Islands',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                208 => [
                        'id'         => '209',
                        'code'       => 'fr',
                        'title'      => 'France',
                        'picture_id' => null,
                        'sort'       => '997',
                    ],
                209 => [
                        'id'         => '210',
                        'code'       => 'gf',
                        'title'      => 'French Guiana',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                210 => [
                        'id'         => '211',
                        'code'       => 'pf',
                        'title'      => 'French Polynesia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                211 => [
                        'id'         => '212',
                        'code'       => 'hr',
                        'title'      => 'Croatia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                212 => [
                        'id'         => '213',
                        'code'       => 'cf',
                        'title'      => 'Central African Republic',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                213 => [
                        'id'         => '214',
                        'code'       => 'td',
                        'title'      => 'Chad',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                214 => [
                        'id'         => '215',
                        'code'       => 'cz',
                        'title'      => 'Czech Republic',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                215 => [
                        'id'         => '216',
                        'code'       => 'cl',
                        'title'      => 'Chile',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                216 => [
                        'id'         => '217',
                        'code'       => 'ch',
                        'title'      => 'Switzerland',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                217 => [
                        'id'         => '218',
                        'code'       => 'se',
                        'title'      => 'Sweden',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                218 => [
                        'id'         => '219',
                        'code'       => 'sj',
                        'title'      => 'Svalbard and Jan Mayen',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                219 => [
                        'id'         => '220',
                        'code'       => 'lk',
                        'title'      => 'Sri Lanka',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                220 => [
                        'id'         => '221',
                        'code'       => 'ec',
                        'title'      => 'Ecuador',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                221 => [
                        'id'         => '222',
                        'code'       => 'gq',
                        'title'      => 'Equatorial Guinea',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                222 => [
                        'id'         => '223',
                        'code'       => 'er',
                        'title'      => 'Eritrea',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                223 => [
                        'id'         => '224',
                        'code'       => 'et',
                        'title'      => 'Ethiopia',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                224 => [
                        'id'         => '226',
                        'code'       => 'kr',
                        'title'      => 'South Korea',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                225 => [
                        'id'         => '227',
                        'code'       => 'za',
                        'title'      => 'South Africa',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                226 => [
                        'id'         => '228',
                        'code'       => 'jm',
                        'title'      => 'Jamaica',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                227 => [
                        'id'         => '229',
                        'code'       => 'jp',
                        'title'      => 'Japan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                228 => [
                        'id'         => '230',
                        'code'       => 'me',
                        'title'      => 'Montenegro',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                229 => [
                        'id'         => '231',
                        'code'       => 'dj',
                        'title'      => 'Djibouti',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                230 => [
                        'id'         => '232',
                        'code'       => 'rs',
                        'title'      => 'South Sudan',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                231 => [
                        'id'         => '233',
                        'code'       => 'sx',
                        'title'      => 'Vatican',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                232 => [
                        'id'         => '234',
                        'code'       => 'ss',
                        'title'      => 'Sint Maarten',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
                233 => [
                        'id'         => '235',
                        'code'       => 'va',
                        'title'      => 'Bonaire, Sint Eustatius and Saba',
                        'picture_id' => null,
                        'sort'       => '100',
                    ],
        ];
    }
}
